### ISSUE TITLE
Cannot inject service

### ISSUE THREAD

**Issue by gossi** [rwjblue/sparkles-component#1]
Do get the error message:

```
Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.
```

**Comment by rwjblue** [comment]
Thanks for reporting! Should be able to make this work pretty easily...

If you have time, a failing test case would be really helpful (to make sure I handle your specific use case). The tests here are just normal rendering tests so it should be pretty nice/easy to add more...

**Comment by rwjblue** [comment]
Should be fixed now, closing...
