### ISSUE TITLE
sparkles-component blueprint crashes with generate/install command

### ISSUE THREAD

**Issue by gossi** [rwjblue/sparkles-component#20]
When running:

```
ember install sparkles-component
```

ember will pickup the `sparkles-component` blueprint and run this generator. Since this blueprint isn't supposed to be run when installing the package, there is a naming conflict here.
Affects https://github.com/gossi/ember-cli-create/issues/11

**Comment by rwjblue** [comment]
Hmm, this is the reason we specify a defaultBlueprint: 

https://github.com/rwjblue/sparkles-component/blob/e320c6ffba4681fe3cbcb74abcbe24aad7bffef7/package.json#L79

When that is present ember-cli is supposed to use _that_ blueprint instead of the one named for the addon 🤔

**Comment by gossi** [comment]
Ah ok, `ember-cli-create` doesn't check for that value, instead it will look for a blueprint named identical to the addon name. Will need to add this check - thanks.

**Comment by rwjblue** [comment]
Oh, I see. I thought you had mentioned running `ember install` directly...
