### ISSUE TITLE
Classes are not concatenated with those in the splattributes on contextual components

### ISSUE THREAD

**Issue by cibernox** [rwjblue/sparkles-component#7]
I'm not sure if this is a bug in this addon or in ember itself.

It can be reproduced in this repo: https://github.com/cibernox/sparkles-ember-basic-dropdown

The gist of it:

```hbs
<BasicDropdown as |dd|>
  <dd.trigger class="custom-class" title="foo">Content</dd.trigger>
</BasicDropdown>
```

```hbs
{{!-- basic-dropdown.hbs --}}
{{yield (hash trigger=(component "basic-dropdown-trigger"))}}
```

```hbs
{{!-- basic-dropdown-trigger.hbs --}}
<button class="default-class" ...attributes>
```

The rendered html is:

```html
<button class="default-class" title="foo">
```

Seems that the splattibutes are applied (the `title="foo"` is added to the button) but attributes present in the element receiving the splattibutes are not merged.

This however works ok in non-contextual components, like the root `<BasicDropdown>` for instance.

**Comment by rwjblue** [comment]
Ya, almost certainly a bug in Ember itself. Would you mind PR’ing a failing test to Ember? I think you can take [this test](https://github.com/emberjs/ember.js/blob/5d1b619665def7fb584a3ce8ebb286327e5dd0b8/packages/%40ember/-internals/glimmer/tests/integration/components/angle-bracket-invocation-test.js#L733) and make it like this yielded setup. I expect it will fail in the same way...

**Comment by cibernox** [comment]
This is working with the latest ember release (3.4)
